// Shared Supabase backend for every Review System package (one backend,
// many projects — matches template/ being reused per project).
// Fill these in once after creating the Supabase project; every package
// generated by tools/import-project.mjs copies this file as-is, so you
// only edit it here in template/, not per project.
window.SUPABASE_CONFIG = {
  url: 'https://jiygozeigretzermxwgp.supabase.co',
  anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppeWdvemVpZ3JldHplcm14d2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkxMzc2NDMsImV4cCI6MjEwNDcxMzY0M30.EyEYPM_r04Vt_3zpGg1KpkZ2VWPPtxnwnKNomgIjl0k',
};
